### ISSUE TITLE
Get the new web client up an running

### ISSUE THREAD

**Issue by Fish360** [Fish360/Journal#13]
#### Summary
The objective of this task is to get the production site of Fish360 Journal up and running on heroku.

**Comment by Fish360** [comment]
@jannunzi 

What are the sub-tasks / details for this task?

**Comment by yashsnehalshah** [comment]
@Fish360 Well there is one version running at https://fish360.herokuapp.com/#/ but that will need to be updated after our planned tasks have been performed.

**Comment by Fish360** [comment]
#### 01-MAR-2018 MEETING MINUTES

* Tested.
* Works.
* Closing.
