### ISSUE TITLE
Rename mobile desktop icon: Android

### ISSUE THREAD

**Issue by Fish360** [Fish360/Journal#22]
#### Summary

Rename mobile desktop icon name from "FishingJournal" to "Fish360 Journal".  

#### Fig. 1

![icone_name_375](https://cloud.githubusercontent.com/assets/2513400/24082870/c5848d68-0ca2-11e7-9354-b1f47415773f.PNG)

**Comment by yashsnehalshah** [comment]
Sure @Fish360 

While testing on my android device, i found that the icon name is Fish360 and also the icon displays logo of "MIT App Inventor"(Tool used to build APK) rather than the image of red fish. Will figure out how to change that and come up with an updated APK.

**Comment by yashsnehalshah** [comment]
Julio, I have built an updated APK with the required icon logo and name on my local machine. I am not sure how to publish that on the play store and would have to look into that. Here are the screens for your reference(Let me know if this doesnt seem the right place to share screenshots, i can then post on hangouts)

![screenshot_2018-02-06-21-31-55](https://user-images.githubusercontent.com/22141408/35895928-afd10412-0b87-11e8-9d16-e62d285e7d8e.png)
![screenshot_2018-02-06-21-32-25](https://user-images.githubusercontent.com/22141408/35895932-b3a56bdc-0b87-11e8-98e1-425f1621fa42.png)

@Fish360

**Comment by Fish360** [comment]
@yashsnehalshah 

Looking good!

Posting screen shots here is fine.

**Comment by yashsnehalshah** [comment]
@Fish360 

Julio, Ankita has informed that she is out of town for some interviews and would jump in to work once she is back in a day or two. Till then, I am happy to work on any of her assigned tasks if needed. Please feel free to assign me any of her tasks that need immediate attention.

Thanks.

**Comment by Fish360** [comment]
@yashsnehalshah,

I have re-assigned the following two critical path issues to you:

* Get the new web client up an running #13
* Create a new iframe to embed on a webpage #14

**Comment by yashsnehalshah** [comment]
Ok sure @Fish360 

Just to clear up, the goal of #13 is to have the app deployed on heroku to be addressed from https://www.fish360.net/ right?

And i couldn't really understand the #14 task. Can you please shed some more light on the details as to what exactly is required?

PS Pl take your time to reply as its a working day and you might be busy with work as well. You can always ask to DND and reply at your convenience:-)

**Comment by Fish360** [comment]
@yashsnehalshah 

Mea culpa.  I have added descriptions to task #13 and  task #14.

**Comment by Fish360** [comment]
Tested and confirmed fix on my Android tablet.

Closing.
