### ISSUE TITLE
Create QA Machine on Heroku

### ISSUE THREAD

**Issue by jannunzi** [Fish360/Journal#60]
Have QA Machine deploy from QA branch.
Configure environment variables such as keys in new server.

**Comment by Fish360** [comment]
@jannunzi 

I have targeted this issue to Sprint 2.
Please assign some one to this issue.

**Comment by Fish360** [comment]
@jannunzi, can we close this issue now?

**Comment by shohitb** [comment]
created a QA environment on heroku to deploy new code and test it before merging to production environment.
