### ISSUE TITLE
Create QA branch on github

### ISSUE THREAD

**Issue by jannunzi** [Fish360/Journal#61]
Branch off of the latest master branch
Lock Master branch so that only admin can merge to master
All subsequent PRs will be to merge into this new QA branch

**Comment by Fish360** [comment]
@jannunzi 

I have targeted this issue to Sprint 2.
Please assign some one to this issue.

**Comment by Fish360** [comment]
@jannunzi, can we close this issue now?

**Comment by shohitb** [comment]
Created a QA branch with the name "fish360-test-env"
