### ISSUE TITLE
Create a new QA mlab Mongo instance for QA machine

### ISSUE THREAD

**Issue by jannunzi** [Fish360/Journal#62]
Export current production data and import into new QA mlab instance
Configure new QA Heroku machine to use this new QA mlab instance

**Comment by Fish360** [comment]
@jannunzi 

I have targeted this issue to Sprint 2.
Please assign some one to this issue.

**Comment by Fish360** [comment]
@schanx001 and Jose,

While testing the issues in Sprint 1, I notice that the data created in the test environment (https://fish360-journal-test.herokuapp.com) shows up in the production environment (https://fish360.herokuapp.com), and vice versa.

Is the purpose of this issue to to create a new db for the test environment?

**Comment by schanx001** [comment]
Yes. The purpose is to create a new db for test. Exporting the production db and importing it into a new one.

**Comment by shohitb** [comment]
created a database for QA environment.
